#!/usr/bin/env python3
"""Create lupdate input for TranslationManager's generic DynamicUI context.

The application deliberately keeps this catalog generated: it is a list of
source-language candidates, not a translation file.  A separate translation
tool can run the CMake ``SC2DataHelper_lupdate`` target, fill the resulting TS
entries, and leave the application code untouched.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


# The project consistently uses ordinary C++ string literals for visible UI
# text.  Keeping the original escaped spelling lets lupdate parse the same
# source value C++ uses at runtime.
STRING_LITERAL = re.compile(r'(?<![A-Za-z0-9_])(?:u8|u|U|L)?"((?:\\.|[^"\\\r\n])*)"')


def discover_string_values(text: str) -> list[str]:
    """Return source values, joining adjacent C++ string literals.

    ``QStringLiteral("first" " second")`` has one runtime source value,
    while a plain regex match sees two.  DynamicUI translates the joined value,
    so the generated lupdate input must do the same.
    """
    matches = list(STRING_LITERAL.finditer(text))
    values: list[str] = []
    index = 0
    while index < len(matches):
        match = matches[index]
        value = match.group(1)
        end = match.end()
        index += 1
        while index < len(matches):
            next_match = matches[index]
            if not text[end:next_match.start()].isspace():
                break
            value += next_match.group(1)
            end = next_match.end()
            index += 1
        values.append(value)
    return values


def is_catalog_candidate(value: str) -> bool:
    """Discard obvious implementation-only literals while retaining UI text."""
    stripped = value.strip()
    if not stripped:
        return False
    if stripped.startswith((":/", "http://", "https://")):
        return False
    # Keep compact slash and angle-bracket captions too.  They occur in the
    # actual UI (for example "N/A", "Actor/Model", and "<unnamed>") and are
    # indistinguishable from implementation paths without an incomplete,
    # brittle allow-list.  This catalog is deliberately over-inclusive: an
    # extra source key is harmless, while a missing visible caption prevents a
    # translation at runtime.
    if not any(character.isalpha() for character in stripped):
        return False
    return True


def discover_literals(source_root: Path) -> list[str]:
    values: set[str] = set()
    for suffix in ("*.cpp", "*.h"):
        for path in source_root.rglob(suffix):
            if any(part in {"build", "target", "third_party"} for part in path.parts):
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            for value in discover_string_values(text):
                if is_catalog_candidate(value):
                    values.add(value)
    return sorted(values)


def write_catalog(output: Path, values: list[str]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/generate_dynamic_ui_catalog.py. Do not edit.",
        "#include <QCoreApplication>",
        "",
        "namespace {",
        "[[maybe_unused]] const char *const dynamicUiSources[] = {",
    ]
    lines.extend(f'    QT_TRANSLATE_NOOP("DynamicUI", "{value}"),' for value in values)
    lines.extend(["};", "} // namespace", ""])
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    write_catalog(args.output, discover_literals(args.source_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
